version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: wow_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wow_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  php:
    build: .
    container_name: wow_php
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - db
    volumes:
      - ./src:/var/www/html # ✅ this enables live updates
      - ./assets:/var/www/html/assets

volumes:
  db_data:
