version: '3.8'

services:
  db:
    image: postgres:15
    container_name: wow_postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: wow_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init-scripts:/docker-entrypoint-initdb.d

  php:
    build: .
    container_name: wow_php
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - db
    entrypoint: ["/entrypoint.sh"]
    volumes:
      - ./src:/var/www/html
      - ./assets:/var/www/html/assets
      - ./entrypoint.sh:/entrypoint.sh

volumes:
  db_data:


